### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#898]
symbol-desktop-wallet-win-0.13.7.exe

![2021-01-15 19-32-34-797](https://user-images.githubusercontent.com/59822825/104715241-9f41bc00-5769-11eb-9633-2cff2008e2f4.png)

**Comment by soul-surfer** [comment]
I can confirm this bug exists in 0.13.7 on Linux.  I downloaded the .xz archive for 64-bit linux.  Extracted the folder and ran ./symbol-desktop-wallet.

kernel: 5.10.2-2 x86_64

No window appears.  The following is the error that is displayed in the console.

    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: Cannot find module 'electron-localshortcut'
    Require stack:
     /home/username/Folder/Symbol-0.13.7/resources/app.asar/public/build.js
 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manjaro/Wallets/Symbol-0.13.7/resources/app.asar/public/build.js:8:31)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

**Comment by cryptoBeliever** [comment]
Should be solved in 0.13.8
